# Generated by Django 5.0.2 on 2024-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_signupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=12)),
            ],
        ),
    ]
